import 'package:flutter/material.dart';

class ChatIconStyle {
  const ChatIconStyle({
    required this.key,
    required this.label,
    required this.topic,
    required this.group,
    required this.icon,
    required this.color,
    this.variant = 0,
  });
  final String key, label, topic, group;
  final IconData icon;
  final Color color;
  final int variant;
}

abstract final class ChatAppearance {
  static const groups = [
    'Церковное',
    'Помощь',
    'Общение',
    'Спорт и активности',
    'Поездки',
    'Обучение',
    'События',
  ];
  static const library = <ChatIconStyle>[
    ChatIconStyle(
      key: 'chat_1',
      label: 'Общение · 1',
      topic: 'Общение',
      group: 'Общение',
      icon: Icons.chat_bubble_rounded,
      color: Color(0xff2787D0),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'chat_2',
      label: 'Общение · 2',
      topic: 'Общение',
      group: 'Общение',
      icon: Icons.forum_rounded,
      color: Color(0xff40A86B),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'chat_3',
      label: 'Общение · 3',
      topic: 'Общение',
      group: 'Общение',
      icon: Icons.question_answer_rounded,
      color: Color(0xffD95460),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'chat_4',
      label: 'Общение · 4',
      topic: 'Общение',
      group: 'Общение',
      icon: Icons.record_voice_over_rounded,
      color: Color(0xff497BA8),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'chat_5',
      label: 'Общение · 5',
      topic: 'Общение',
      group: 'Общение',
      icon: Icons.waving_hand_rounded,
      color: Color(0xff13A3A5),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'announcements_1',
      label: 'Объявления · 1',
      topic: 'Объявления',
      group: 'События',
      icon: Icons.campaign_rounded,
      color: Color(0xff536BCC),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'announcements_2',
      label: 'Объявления · 2',
      topic: 'Объявления',
      group: 'События',
      icon: Icons.notifications_active_rounded,
      color: Color(0xff9464CF),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'announcements_3',
      label: 'Объявления · 3',
      topic: 'Объявления',
      group: 'События',
      icon: Icons.volume_up_rounded,
      color: Color(0xffE18B36),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'announcements_4',
      label: 'Объявления · 4',
      topic: 'Объявления',
      group: 'События',
      icon: Icons.announcement_rounded,
      color: Color(0xff2787D0),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'announcements_5',
      label: 'Объявления · 5',
      topic: 'Объявления',
      group: 'События',
      icon: Icons.notification_important_rounded,
      color: Color(0xff40A86B),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'news_1',
      label: 'Новости · 1',
      topic: 'Новости',
      group: 'События',
      icon: Icons.feed_rounded,
      color: Color(0xff13A3A5),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'news_2',
      label: 'Новости · 2',
      topic: 'Новости',
      group: 'События',
      icon: Icons.newspaper_rounded,
      color: Color(0xffD96398),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'news_3',
      label: 'Новости · 3',
      topic: 'Новости',
      group: 'События',
      icon: Icons.rss_feed_rounded,
      color: Color(0xffC49A3B),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'news_4',
      label: 'Новости · 4',
      topic: 'Новости',
      group: 'События',
      icon: Icons.public_rounded,
      color: Color(0xff536BCC),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'news_5',
      label: 'Новости · 5',
      topic: 'Новости',
      group: 'События',
      icon: Icons.dynamic_feed_rounded,
      color: Color(0xff9464CF),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'craft_1',
      label: 'Рукоделие · 1',
      topic: 'Рукоделие',
      group: 'Обучение',
      icon: Icons.content_cut_rounded,
      color: Color(0xff40A86B),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'craft_2',
      label: 'Рукоделие · 2',
      topic: 'Рукоделие',
      group: 'Обучение',
      icon: Icons.palette_rounded,
      color: Color(0xffD95460),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'craft_3',
      label: 'Рукоделие · 3',
      topic: 'Рукоделие',
      group: 'Обучение',
      icon: Icons.brush_rounded,
      color: Color(0xff497BA8),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'craft_4',
      label: 'Рукоделие · 4',
      topic: 'Рукоделие',
      group: 'Обучение',
      icon: Icons.auto_awesome_rounded,
      color: Color(0xff13A3A5),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'craft_5',
      label: 'Рукоделие · 5',
      topic: 'Рукоделие',
      group: 'Обучение',
      icon: Icons.draw_rounded,
      color: Color(0xffD96398),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'sport_1',
      label: 'Спорт · 1',
      topic: 'Спорт',
      group: 'Спорт и активности',
      icon: Icons.sports_soccer_rounded,
      color: Color(0xff9464CF),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'sport_2',
      label: 'Спорт · 2',
      topic: 'Спорт',
      group: 'Спорт и активности',
      icon: Icons.fitness_center_rounded,
      color: Color(0xffE18B36),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'sport_3',
      label: 'Спорт · 3',
      topic: 'Спорт',
      group: 'Спорт и активности',
      icon: Icons.directions_run_rounded,
      color: Color(0xff2787D0),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'sport_4',
      label: 'Спорт · 4',
      topic: 'Спорт',
      group: 'Спорт и активности',
      icon: Icons.sports_basketball_rounded,
      color: Color(0xff40A86B),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'sport_5',
      label: 'Спорт · 5',
      topic: 'Спорт',
      group: 'Спорт и активности',
      icon: Icons.pool_rounded,
      color: Color(0xffD95460),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'games_1',
      label: 'Настольные игры · 1',
      topic: 'Настольные игры',
      group: 'Спорт и активности',
      icon: Icons.casino_rounded,
      color: Color(0xffD96398),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'games_2',
      label: 'Настольные игры · 2',
      topic: 'Настольные игры',
      group: 'Спорт и активности',
      icon: Icons.extension_rounded,
      color: Color(0xffC49A3B),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'games_3',
      label: 'Настольные игры · 3',
      topic: 'Настольные игры',
      group: 'Спорт и активности',
      icon: Icons.sports_esports_rounded,
      color: Color(0xff536BCC),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'games_4',
      label: 'Настольные игры · 4',
      topic: 'Настольные игры',
      group: 'Спорт и активности',
      icon: Icons.toys_rounded,
      color: Color(0xff9464CF),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'games_5',
      label: 'Настольные игры · 5',
      topic: 'Настольные игры',
      group: 'Спорт и активности',
      icon: Icons.grid_view_rounded,
      color: Color(0xffE18B36),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'travel_1',
      label: 'Поездки · 1',
      topic: 'Поездки',
      group: 'Поездки',
      icon: Icons.directions_bus_rounded,
      color: Color(0xffD95460),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'travel_2',
      label: 'Поездки · 2',
      topic: 'Поездки',
      group: 'Поездки',
      icon: Icons.route_rounded,
      color: Color(0xff497BA8),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'travel_3',
      label: 'Поездки · 3',
      topic: 'Поездки',
      group: 'Поездки',
      icon: Icons.hiking_rounded,
      color: Color(0xff13A3A5),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'travel_4',
      label: 'Поездки · 4',
      topic: 'Поездки',
      group: 'Поездки',
      icon: Icons.train_rounded,
      color: Color(0xffD96398),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'travel_5',
      label: 'Поездки · 5',
      topic: 'Поездки',
      group: 'Поездки',
      icon: Icons.sailing_rounded,
      color: Color(0xffC49A3B),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'volunteer_1',
      label: 'Волонтёры · 1',
      topic: 'Волонтёры',
      group: 'Помощь',
      icon: Icons.volunteer_activism_rounded,
      color: Color(0xffE18B36),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'volunteer_2',
      label: 'Волонтёры · 2',
      topic: 'Волонтёры',
      group: 'Помощь',
      icon: Icons.handshake_rounded,
      color: Color(0xff2787D0),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'volunteer_3',
      label: 'Волонтёры · 3',
      topic: 'Волонтёры',
      group: 'Помощь',
      icon: Icons.diversity_1_rounded,
      color: Color(0xff40A86B),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'volunteer_4',
      label: 'Волонтёры · 4',
      topic: 'Волонтёры',
      group: 'Помощь',
      icon: Icons.front_hand_rounded,
      color: Color(0xffD95460),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'volunteer_5',
      label: 'Волонтёры · 5',
      topic: 'Волонтёры',
      group: 'Помощь',
      icon: Icons.eco_rounded,
      color: Color(0xff497BA8),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'help_1',
      label: 'Помощь · 1',
      topic: 'Помощь',
      group: 'Помощь',
      icon: Icons.favorite_rounded,
      color: Color(0xffC49A3B),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'help_2',
      label: 'Помощь · 2',
      topic: 'Помощь',
      group: 'Помощь',
      icon: Icons.redeem_rounded,
      color: Color(0xff536BCC),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'help_3',
      label: 'Помощь · 3',
      topic: 'Помощь',
      group: 'Помощь',
      icon: Icons.savings_rounded,
      color: Color(0xff9464CF),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'help_4',
      label: 'Помощь · 4',
      topic: 'Помощь',
      group: 'Помощь',
      icon: Icons.health_and_safety_rounded,
      color: Color(0xffE18B36),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'help_5',
      label: 'Помощь · 5',
      topic: 'Помощь',
      group: 'Помощь',
      icon: Icons.support_rounded,
      color: Color(0xff2787D0),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'music_1',
      label: 'Музыка · 1',
      topic: 'Музыка',
      group: 'Общение',
      icon: Icons.music_note_rounded,
      color: Color(0xff497BA8),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'music_2',
      label: 'Музыка · 2',
      topic: 'Музыка',
      group: 'Общение',
      icon: Icons.piano_rounded,
      color: Color(0xff13A3A5),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'music_3',
      label: 'Музыка · 3',
      topic: 'Музыка',
      group: 'Общение',
      icon: Icons.headphones_rounded,
      color: Color(0xffD96398),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'music_4',
      label: 'Музыка · 4',
      topic: 'Музыка',
      group: 'Общение',
      icon: Icons.mic_rounded,
      color: Color(0xffC49A3B),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'music_5',
      label: 'Музыка · 5',
      topic: 'Музыка',
      group: 'Общение',
      icon: Icons.library_music_rounded,
      color: Color(0xff536BCC),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'study_1',
      label: 'Учёба · 1',
      topic: 'Учёба',
      group: 'Обучение',
      icon: Icons.school_rounded,
      color: Color(0xff2787D0),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'study_2',
      label: 'Учёба · 2',
      topic: 'Учёба',
      group: 'Обучение',
      icon: Icons.science_rounded,
      color: Color(0xff40A86B),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'study_3',
      label: 'Учёба · 3',
      topic: 'Учёба',
      group: 'Обучение',
      icon: Icons.edit_note_rounded,
      color: Color(0xffD95460),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'study_4',
      label: 'Учёба · 4',
      topic: 'Учёба',
      group: 'Обучение',
      icon: Icons.psychology_rounded,
      color: Color(0xff497BA8),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'study_5',
      label: 'Учёба · 5',
      topic: 'Учёба',
      group: 'Обучение',
      icon: Icons.history_edu_rounded,
      color: Color(0xff13A3A5),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'books_1',
      label: 'Книги · 1',
      topic: 'Книги',
      group: 'Обучение',
      icon: Icons.menu_book_rounded,
      color: Color(0xff536BCC),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'books_2',
      label: 'Книги · 2',
      topic: 'Книги',
      group: 'Обучение',
      icon: Icons.auto_stories_rounded,
      color: Color(0xff9464CF),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'books_3',
      label: 'Книги · 3',
      topic: 'Книги',
      group: 'Обучение',
      icon: Icons.book_rounded,
      color: Color(0xffE18B36),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'books_4',
      label: 'Книги · 4',
      topic: 'Книги',
      group: 'Обучение',
      icon: Icons.local_library_rounded,
      color: Color(0xff2787D0),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'books_5',
      label: 'Книги · 5',
      topic: 'Книги',
      group: 'Обучение',
      icon: Icons.collections_bookmark_rounded,
      color: Color(0xff40A86B),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'photo_1',
      label: 'Фото · 1',
      topic: 'Фото',
      group: 'Общение',
      icon: Icons.photo_camera_rounded,
      color: Color(0xff13A3A5),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'photo_2',
      label: 'Фото · 2',
      topic: 'Фото',
      group: 'Общение',
      icon: Icons.photo_library_rounded,
      color: Color(0xffD96398),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'photo_3',
      label: 'Фото · 3',
      topic: 'Фото',
      group: 'Общение',
      icon: Icons.camera_rounded,
      color: Color(0xffC49A3B),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'photo_4',
      label: 'Фото · 4',
      topic: 'Фото',
      group: 'Общение',
      icon: Icons.movie_rounded,
      color: Color(0xff536BCC),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'photo_5',
      label: 'Фото · 5',
      topic: 'Фото',
      group: 'Общение',
      icon: Icons.videocam_rounded,
      color: Color(0xff9464CF),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'ideas_1',
      label: 'Идеи · 1',
      topic: 'Идеи',
      group: 'Общение',
      icon: Icons.lightbulb_rounded,
      color: Color(0xff40A86B),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'ideas_2',
      label: 'Идеи · 2',
      topic: 'Идеи',
      group: 'Общение',
      icon: Icons.tips_and_updates_rounded,
      color: Color(0xffD95460),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'ideas_3',
      label: 'Идеи · 3',
      topic: 'Идеи',
      group: 'Общение',
      icon: Icons.rocket_launch_rounded,
      color: Color(0xff497BA8),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'ideas_4',
      label: 'Идеи · 4',
      topic: 'Идеи',
      group: 'Общение',
      icon: Icons.emoji_objects_rounded,
      color: Color(0xff13A3A5),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'ideas_5',
      label: 'Идеи · 5',
      topic: 'Идеи',
      group: 'Общение',
      icon: Icons.hub_rounded,
      color: Color(0xffD96398),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'youth_1',
      label: 'Молодёжь · 1',
      topic: 'Молодёжь',
      group: 'Общение',
      icon: Icons.groups_rounded,
      color: Color(0xff9464CF),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'youth_2',
      label: 'Молодёжь · 2',
      topic: 'Молодёжь',
      group: 'Общение',
      icon: Icons.diversity_3_rounded,
      color: Color(0xffE18B36),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'youth_3',
      label: 'Молодёжь · 3',
      topic: 'Молодёжь',
      group: 'Общение',
      icon: Icons.emoji_people_rounded,
      color: Color(0xff2787D0),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'youth_4',
      label: 'Молодёжь · 4',
      topic: 'Молодёжь',
      group: 'Общение',
      icon: Icons.group_add_rounded,
      color: Color(0xff40A86B),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'youth_5',
      label: 'Молодёжь · 5',
      topic: 'Молодёжь',
      group: 'Общение',
      icon: Icons.celebration_rounded,
      color: Color(0xffD95460),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'church_1',
      label: 'Церковное · 1',
      topic: 'Церковное',
      group: 'Церковное',
      icon: Icons.church_rounded,
      color: Color(0xffD96398),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'church_2',
      label: 'Церковное · 2',
      topic: 'Церковное',
      group: 'Церковное',
      icon: Icons.wb_sunny_rounded,
      color: Color(0xffC49A3B),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'church_3',
      label: 'Церковное · 3',
      topic: 'Церковное',
      group: 'Церковное',
      icon: Icons.notifications_rounded,
      color: Color(0xff536BCC),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'church_4',
      label: 'Церковное · 4',
      topic: 'Церковное',
      group: 'Церковное',
      icon: Icons.flare_rounded,
      color: Color(0xff9464CF),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'church_5',
      label: 'Церковное · 5',
      topic: 'Церковное',
      group: 'Церковное',
      icon: Icons.church_rounded,
      color: Color(0xffE18B36),
      variant: 4,
    ),
    ChatIconStyle(
      key: 'events_1',
      label: 'События · 1',
      topic: 'События',
      group: 'События',
      icon: Icons.event_rounded,
      color: Color(0xffD95460),
      variant: 0,
    ),
    ChatIconStyle(
      key: 'events_2',
      label: 'События · 2',
      topic: 'События',
      group: 'События',
      icon: Icons.calendar_month_rounded,
      color: Color(0xff497BA8),
      variant: 1,
    ),
    ChatIconStyle(
      key: 'events_3',
      label: 'События · 3',
      topic: 'События',
      group: 'События',
      icon: Icons.festival_rounded,
      color: Color(0xff13A3A5),
      variant: 2,
    ),
    ChatIconStyle(
      key: 'events_4',
      label: 'События · 4',
      topic: 'События',
      group: 'События',
      icon: Icons.star_rounded,
      color: Color(0xffD96398),
      variant: 3,
    ),
    ChatIconStyle(
      key: 'events_5',
      label: 'События · 5',
      topic: 'События',
      group: 'События',
      icon: Icons.local_activity_rounded,
      color: Color(0xffC49A3B),
      variant: 4,
    ),
  ];
  static const aliases = <String, String>{
    'chat': 'chat_1',
    'announcements': 'announcements_1',
    'news': 'news_1',
    'book': 'books_1',
    'games': 'games_1',
    'location': 'travel_2',
    'rules': 'books_3',
    'help': 'help_1',
    'sport': 'sport_1',
    'craft': 'craft_1',
    'music': 'music_1',
    'prayer': 'church_1',
    'family': 'youth_1',
  };
  // Compatibility for existing editors and administration screens.
  static final icons = <String, ({String label, IconData icon})>{
    'auto': (label: 'Автоматически', icon: Icons.auto_awesome_rounded),
    for (final entry in aliases.entries)
      entry.key: (
        label: resolve(entry.key).topic,
        icon: resolve(entry.key).icon,
      ),
    for (final item in library) item.key: (label: item.label, icon: item.icon),
  };
  static ChatIconStyle resolve(
    String key, {
    String title = '',
    String description = '',
    String seed = '',
  }) {
    final canonical = aliases[key] ?? key;
    for (final item in library) {
      if (item.key == canonical) return item;
    }
    String? topicFor(String input) {
      final text = input.toLowerCase().replaceAll('ё', 'е');
      const themes = <String, String>{
        'announcements': r'объявлен|важно|объявить',
        'news': r'новост|вести|новое',
        'craft': r'рукодел|вязани|шить|мастерск|творче',
        'sport': r'спорт|футбол|бег|трениров',
        'games': r'настол|игр|шахмат',
        'travel': r'поезд|путеш|палом|сплав|поход',
        'volunteer': r'волонт|добровол',
        'help': r'помощ|сбор|поддерж|пожертв|благотвор',
        'music': r'музык|хор|пени|песн',
        'study': r'учеб|обуч|лекци|урок',
        'books': r'книг|чтени|материал|библиот',
        'photo': r'фото|снимк|видео|галере',
        'ideas': r'иде|предлож|проект|план',
        'church': r'храм|церков|молит|служб|литург|православ|евангел|монастыр',
        'events': r'событ|празд|мероприят|расписан',
        'youth': r'молод|семь|друз|встреч',
        'chat': r'болтал|общени|бесед|разговор',
      };
      for (final theme in themes.entries) {
        if (RegExp(theme.value).hasMatch(text)) return theme.key;
      }
      return null;
    }

    final topic = topicFor(title) ?? topicFor(description) ?? 'chat';
    var hash = 0;
    for (final unit in '$seed$title'.codeUnits) {
      hash = (hash * 31 + unit) & 0x7fffffff;
    }
    return library.firstWhere((item) => item.key == '${topic}_${hash % 5 + 1}');
  }

  static Color color(String key) => resolve(key).color;
}
